## 1 可能发生内存泄漏的情况

1. 中间省略的代码部分也许会抛出异常，导致最后的 delete ptr 得不到执⾏  


```cpp
void foo
{
    bar* ptr = new bar();
    ......
    delete ptr;
}
```

2. 分配和释放不在⼀个函数⾥  


```cpp
bar* make_ptr(...)
{
    try
    {
        bar* ptr = new bar();
    }
    catch(...)
    {
        delete ptr;
        throw;
    }
    return ptr;
}

void foo()
{
    bar* ptr = make_ptr(...);
    ...
    delete ptr;
}
```

